---
# tasks file for mylb

- name : "Installing haproxy.. "
  package :
    name : "{{ package }}"
    state : present

- name : "Configuring the HAPROXY"
  template :
    src : haproxy.cfg.j2
    dest : "/etc/haproxy/haproxy.cfg"
  notify : haproxy

- name : "Starting haproxy server"
  service :
    name : "{{ service  }}"
    state : started
  

