---
# tasks file for myapache
- name : "Installing httpd package and PHP"
  yum :
    name : "{{ package }}"
    state : present
  loop : "{{ package  }}"

      
- name : "Copying webpages to server"
  copy :
    src : "index.php"
    dest : "{{ document_root  }}"
  notify : "web_status"

- name : "Starting httpd services"
  service :
    name : "{{ service  }}"
    state : started

